# render.yaml
services:
  # Backend API Service
  - type: web
    name: supplier-risk-api
    env: node
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:server
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false

  # Frontend Static Site (Corrected Configuration)
  - type: web
    name: supplier-risk-client
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:client
    outputDir: ./public
    routes:
      - type: rewrite
        source: /api/:path*
        destination: ${supplier-risk-api.url}/api/:path*

      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: supplier-db
    plan: free
    databaseName: supplier_risk_db
    postgresMajorVersion: 16