# render.yaml
services:
  # Backend API Service (Web Service)
  - type: web
    name: supplier-risk-api
    env: node
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:server
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false

  # Frontend UI Service (Static Site) - Corrected type
  - type: static_site  # Changed from 'static' to 'static_site'
    name: supplier-risk-client
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:client
    publishDir: ./public
    routes:
      # Proxy API requests using service reference variable
      - type: rewrite
        source: /api/:path*
        destination: ${supplier-risk-api.url}/api/:path*  # Uses Render's service reference

      # SPA Fallback
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: supplier-db
    plan: free
    databaseName: supplier_risk_db
    postgresMajorVersion: 16