# render.yaml
services:
  # Backend API Service (Node.js)
  - type: web
    name: supplier-risk-api
    env: node
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:server
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false  # Set this value in Render Dashboard

  # Frontend Service (Static Site) - Correct Configuration
  - type: web  # Static sites now use "web" type with `static` environment
    name: supplier-risk-client
    env: static  # Critical: Marks this as a static site
    rootDir: .
    plan: free
    buildCommand: |
      npm install
      npm run build:client
    publishDir: ./public  # Where your static files are built
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://supplier-risk-api.onrender.com/api/:path*  # Hardcode URL or use Render variable

      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: supplier-db
    plan: free
    databaseName: supplier_risk_db
    postgresMajorVersion: 16